# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 3.4.2
_src_path: gh:epics-containers/ec-services-template
beamline: bl02t
cluster_namespace: local
description: beamline bl02t IOC Instances and Services
git_platform: github.com
github_org: gilesknap
repo_uri: git@github.com:gilesknap/bl02t.git
type: beamline
