apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bl02t
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: hgv27681
  destination:
    name: argus
    namespace: hgv27681
  source:
    path: apps
    repoURL: https://github.com/gilesknap/bl02t.git
    targetRevision: HEAD
    helm:
      valuesObject:
        spec:
          project: hgv27681
          destination:
            name: argus
            namespace: hgv27681
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
