# A Helm Chart for an IOC instance
apiVersion: v2
name: ec-service

version: 1.0.0

type: application

dependencies:
  - name: ioc-instance
    version: 3.5.4+b7
    repository: "oci://ghcr.io/epics-containers"
    #repository: file:///scratch/hgv27681/work/ec-helm-charts/Charts/ioc-instance
